name: Publish Docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.repository }}
  REPO_OWNER: ${GITHUB_REPOSITORY_OWNER@L}

jobs:
  build:
    permissions: 
      packages: write
      contents: read
      
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          install: true

      - name: Log in to GitHub Container Registry
        id: login-ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.REPO_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.0
        with:
          images: ${{ steps.login-ghcr.outputs.registry }}/${{ env.REPO_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
