name: CI

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, review_requested, assigned]
  merge_group:

jobs:
  shared-tests:
    name: Shared Test Suite
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache pip
        uses: actions/cache@v3
        env:
          requirements: ${{ hashFiles('shared/requirements.txt') }}
          requirements-dev: ${{ hashFiles('shared/requirements-dev.txt') }}
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-test-${{ env.requirements }}-${{ env.requirements-dev }}

      - name: Install dependencies shared
        run: |
          pip install --upgrade pip
          pip install -r shared/requirements-dev.txt

      - name: Run tests shared
        run: |
          pytest
